name: Metrics
on:
  schedule: 
    - cron: "0 20 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics

          template: classic
          base: header, activity, community, repositories
          repositories_affiliations: ''

          plugin_pagespeed: yes
          #plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          plugin_languages: yes
          plugin_languages_details: percentage

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
